### PR TITLE
fix: update methods signatures

### PR DESCRIPTION
**Pull request by hu9osaez**

### CODE REVIEW

**Comment by it-can** [comment]
@flugg can you merge this please?

**Comment by jackkitley** [comment]
@flugg bump

**Comment by it-can** [comment]
@flugg please?

**Comment by flugg** [comment]
Hi guys, sorry for the long wait. As an avid open-source user myself, I know the frustration when things aren't kept up-to-date. It's been increasingly harder to find the time for personal projects like this. With that said, thanks for the pull request! I'll make sure to tag a minor release as well.

**Pull request merged**
